CAD_DOMAINS = [
    # ── Aerospace & Aviation ──────────────────────────────────────────────────
    "Aircraft Fuselage",
    "Aircraft Wings",
    "Aircraft Landing Gear",
    "Aircraft Engine Nacelles",
    "Jet Engine Components",
    "Turbine Blades",
    "Compressor Discs",
    "Combustion Chambers",
    "Rocket Nozzles",
    "Rocket Fuel Tanks",
    "Satellite Structures",
    "Satellite Solar Panels",
    "Spacecraft Chassis",
    "Re-entry Vehicles",
    "Launch Vehicle Fairings",
    "Helicopter Rotors",
    "Helicopter Tail Assemblies",
    "UAV / Drone Frames",
    "Drone Propellers",
    "Drone Arms",
    "Fixed-Wing UAV Bodies",
    "Glider Airframes",
    "Hot Air Balloon Baskets",
    "Parachute Deployment Mechanisms",
    "Ejection Seat Components",
    "Avionics Enclosures",
    "Cockpit Instrument Panels",
    "Oxygen Mask Assemblies",
    "Aircraft Seat Frames",
    "Wing Flap Mechanisms",
    "Thrust Reverser Components",
    "Hypersonic Vehicle Skins",
    "Space Telescope Structures",
    "Orbital Station Docking Modules",
    "CubeSat Frames",
    "Nanosatellite Components",
    "Rocket Fins",
    "Payload Adapters",
    "Ground Support Equipment",

    # ── Automotive ────────────────────────────────────────────────────────────
    "Car Body Panels",
    "Car Chassis",
    "Engine Blocks",
    "Cylinder Heads",
    "Pistons",
    "Crankshafts",
    "Camshafts",
    "Connecting Rods",
    "Gearbox Housings",
    "Differential Cases",
    "Driveshafts",
    "Suspension Arms",
    "Steering Knuckles",
    "Brake Calipers",
    "Brake Rotors",
    "Brake Drums",
    "Wheel Hubs",
    "Wheel Rims",
    "Exhaust Manifolds",
    "Exhaust Systems",
    "Catalytic Converter Housings",
    "Turbocharger Components",
    "Intercooler Cores",
    "Radiators",
    "Coolant Pumps",
    "Oil Pans",
    "Intake Manifolds",
    "Throttle Bodies",
    "Fuel Injector Brackets",
    "Fuel Tanks",
    "Fuel Pumps",
    "Dashboard Panels",
    "Door Panels",
    "Door Handles",
    "Window Regulators",
    "Seat Frames",
    "Headrest Mounts",
    "Bumper Brackets",
    "Headlight Housings",
    "Tail Light Assemblies",
    "Mirror Housings",
    "Windshield Wipers",
    "Battery Trays (EV)",
    "Battery Module Housings",
    "Electric Motor Housings",
    "Inverter Enclosures",
    "Charging Port Covers",
    "Subframes",
    "Roll Cages",
    "Racing Car Aerodynamic Wings",
    "Splitters and Diffusers",
    "Skid Plates",
    "Tow Hitches",
    "Roof Rails",
    "Sunroof Frames",
    "Motorcycle Frames",
    "Motorcycle Fairings",
    "Motorcycle Forks",
    "Motorcycle Swingarms",
    "Bicycle Frames",
    "Bicycle Forks",
    "Bicycle Cranksets",
    "Bicycle Derailleurs",
    "Bicycle Stems",
    "Bicycle Handlebars",
    "Scooter Bodies",
    "ATV Frames",
    "Go-Kart Chassis",
    "Truck Cab Structures",
    "Semi-Truck Fifth Wheel",
    "Trailer Hitches",
    "Trailer Frames",
    "Tank Tracks",
    "Armoured Vehicle Hulls",

    # ── Marine & Naval ────────────────────────────────────────────────────────
    "Ship Hulls",
    "Ship Decks",
    "Ship Bulkheads",
    "Ship Propellers",
    "Ship Rudders",
    "Anchor Chains",
    "Anchor Windlasses",
    "Marine Engine Mounts",
    "Outboard Motor Brackets",
    "Boat Cleats",
    "Boat Hatches",
    "Boat Cabin Structures",
    "Submarine Pressure Hulls",
    "Submarine Ballast Tanks",
    "Torpedo Tubes",
    "Naval Gun Mounts",
    "Offshore Platform Structures",
    "Offshore Drilling Equipment",
    "Underwater ROV Frames",
    "Underwater ROV Thrusters",
    "Buoy Structures",
    "Dock Cleats",
    "Davit Arms",
    "Life Raft Canisters",
    "Sailboat Masts",
    "Sailboat Booms",
    "Winch Drums",
    "Anchor Shackles",
    "Marine Valve Bodies",
    "Propeller Shaft Couplings",
    "Hydrofoil Struts",
    "Hydrofoil Foils",
    "Personal Watercraft Hulls",
    "Kayak Hulls",
    "Canoe Hulls",
    "Rowing Shell Structures",
    "Pontoon Frames",
    "Catamaran Hulls",

    # ── Civil & Structural Engineering ───────────────────────────────────────
    "Bridge Trusses",
    "Bridge Girders",
    "Bridge Deck Panels",
    "Cable Stay Anchors",
    "Suspension Bridge Towers",
    "Arch Bridge Ribs",
    "Retaining Walls",
    "Concrete Formwork",
    "Steel Columns",
    "Steel Beams",
    "Connection Plates",
    "Bolt Patterns",
    "Foundation Piles",
    "Pile Caps",
    "Culverts",
    "Drainage Grates",
    "Manhole Covers",
    "Guard Rails",
    "Road Barrier Systems",
    "Tunnel Linings",
    "Tunnel Portal Structures",
    "Overhead Gantry Signs",
    "Traffic Light Poles",
    "Street Light Poles",
    "Utility Poles",
    "Transmission Towers",
    "Communication Masts",
    "Water Towers",
    "Elevated Tanks",
    "Cooling Tower Structures",
    "Chimney Stacks",
    "Silo Structures",
    "Dam Gates",
    "Spillway Structures",
    "Lock Gates",
    "Flood Barrier Panels",
    "Precast Concrete Panels",
    "Staircase Structures",
    "Handrail Systems",
    "Expansion Joints",

    # ── Architecture & Building ───────────────────────────────────────────────
    "Residential Building Structures",
    "Commercial Building Facades",
    "Curtain Wall Systems",
    "Window Frames",
    "Door Frames",
    "Roof Trusses",
    "Roof Panels",
    "Skylight Frames",
    "Space Frame Structures",
    "Cladding Systems",
    "Balcony Railings",
    "Spiral Staircases",
    "Modular Building Units",
    "Prefab Wall Panels",
    "Atrium Structures",
    "Canopy Structures",
    "Pergola Frames",
    "Geodesic Domes",
    "Swimming Pool Structures",
    "Acoustic Ceiling Panels",
    "Raised Floor Systems",
    "Mezzanine Platforms",
    "Elevator Shafts",
    "Escalator Structures",
    "Parking Structure Decks",
    "Green Roof Systems",
    "Solar Panel Mounting Frames",

    # ── Industrial Machinery ──────────────────────────────────────────────────
    "Conveyor Belt Frames",
    "Conveyor Rollers",
    "Conveyor Pulleys",
    "Conveyor Idlers",
    "Conveyor Drive Units",
    "Screw Conveyors",
    "Bucket Elevators",
    "Gearboxes",
    "Gear Trains",
    "Spur Gears",
    "Helical Gears",
    "Bevel Gears",
    "Worm Gears",
    "Planetary Gear Sets",
    "Rack and Pinion Sets",
    "Chain Sprockets",
    "Belt Pulleys",
    "Timing Belt Systems",
    "Couplings",
    "Flexible Couplings",
    "Jaw Couplings",
    "Bearings Housings",
    "Pillow Block Bearings",
    "Flanged Bearings",
    "Linear Bearings",
    "Ball Screws",
    "Lead Screws",
    "Actuator Brackets",
    "Hydraulic Cylinders",
    "Hydraulic Manifolds",
    "Hydraulic Pump Bodies",
    "Pneumatic Cylinders",
    "Pneumatic Fittings",
    "Solenoid Valve Bodies",
    "Control Valve Bodies",
    "Gate Valves",
    "Ball Valves",
    "Butterfly Valves",
    "Check Valves",
    "Pressure Relief Valves",
    "Pipe Flanges",
    "Pipe Elbows",
    "Pipe Tees",
    "Pipe Reducers",
    "Pipe Hangers",
    "Pipe Clamps",
    "Heat Exchangers",
    "Shell and Tube Exchangers",
    "Plate Heat Exchangers",
    "Pressure Vessels",
    "Storage Tanks",
    "Reaction Vessels",
    "Centrifugal Pump Impellers",
    "Pump Casings",
    "Pump Shafts",
    "Compressor Impellers",
    "Compressor Housings",
    "Mixing Tanks",
    "Agitator Blades",
    "Screw Pump Rotors",
    "Filter Housings",
    "Cyclone Separators",
    "Dust Collector Hoppers",
    "Crusher Frames",
    "Grinding Mill Liners",
    "Vibrating Screen Decks",
    "Roller Press Frames",
    "Extrusion Dies",
    "Injection Mould Tooling",
    "Blow Mould Tooling",
    "Stamping Press Dies",
    "Progressive Dies",
    "Deep Draw Tooling",
    "Hydroforming Tools",
    "Forging Dies",
    "Casting Patterns",
    "Sand Cast Moulds",
    "Die Cast Moulds",
    "Investment Cast Wax Patterns",
    "Jigs and Fixtures",
    "Welding Fixtures",
    "Assembly Fixtures",
    "Inspection Gauges",
    "CMM Fixtures",
    "Lathe Chuck Bodies",
    "Milling Vise Bodies",
    "Rotary Table Indexers",
    "Tool Holders",
    "Collet Chucks",
    "Boring Bars",
    "Cutting Tool Inserts",
    "Drill Jig Plates",

    # ── Robotics & Automation ─────────────────────────────────────────────────
    "Robot Base Frames",
    "Robot Arm Links",
    "Robot Wrist Assemblies",
    "End Effectors",
    "Gripper Fingers",
    "Vacuum Suction Cup Mounts",
    "Robot Joint Housings",
    "Servo Motor Brackets",
    "Stepper Motor Mounts",
    "Linear Actuator Frames",
    "SCARA Robot Arms",
    "Delta Robot Platforms",
    "Collaborative Robot Housings",
    "Mobile Robot Chassis",
    "AGV Frames",
    "Gantry Robot Structures",
    "Pick and Place Mechanisms",
    "Cable Management Chains",
    "Robot Tool Changers",
    "Force Torque Sensor Mounts",
    "Vision System Brackets",
    "Exoskeleton Frames",
    "Prosthetic Arm Structures",
    "Prosthetic Leg Structures",
    "Humanoid Robot Skeletons",
    "Soft Robot Actuator Moulds",
    "3D Printer Frames",
    "3D Printer Hotend Mounts",
    "3D Printer Extruder Bodies",
    "CNC Router Frames",
    "CNC Mill Beds",
    "Laser Cutter Gantries",
    "Plasma Cutter Guides",

    # ── Electronics & Electrical ──────────────────────────────────────────────
    "PCB Enclosures",
    "Electrical Control Panels",
    "DIN Rail Mounts",
    "Cable Trays",
    "Junction Boxes",
    "Distribution Boards",
    "Transformer Housings",
    "Switchgear Enclosures",
    "Motor Control Centre Frames",
    "Battery Enclosures",
    "UPS Enclosures",
    "Server Rack Frames",
    "Server Chassis",
    "Data Centre Cooling Units",
    "Heat Sink Designs",
    "Thermal Interface Spreaders",
    "PCB Standoffs",
    "Connector Backshells",
    "Cable Entry Glands",
    "Strain Relief Clamps",
    "Antenna Mounts",
    "RF Shield Cans",
    "EMI Shielding Enclosures",
    "Sensor Housings",
    "Transducer Mounts",
    "LIDAR Mounts",
    "Camera Housings",
    "Lens Barrels",
    "LED Light Housings",
    "Luminaire Frames",
    "Street Light Heads",
    "Solar Panel Frames",
    "Inverter Enclosures (Solar)",
    "Wind Turbine Nacelles",
    "Wind Turbine Blades",
    "Wind Turbine Towers",
    "Generator Housings",
    "Alternator Frames",
    "Motor Stator Housings",
    "Coil Bobbins",
    "Transformer Core Clamps",
    "Busbar Systems",
    "Grounding Clamps",

    # ── Consumer Products ─────────────────────────────────────────────────────
    "Smartphone Cases",
    "Laptop Enclosures",
    "Tablet Housings",
    "Smartwatch Cases",
    "Smartwatch Bands",
    "Wireless Earbuds",
    "Headphone Frames",
    "Speaker Cabinets",
    "Subwoofer Enclosures",
    "Television Stands",
    "Monitor Arms",
    "Keyboard Cases",
    "Mouse Bodies",
    "Game Controller Housings",
    "Console Enclosures",
    "VR Headset Frames",
    "Webcam Mounts",
    "Microphone Stands",
    "Hair Dryer Housings",
    "Electric Shaver Housings",
    "Electric Toothbrush Bodies",
    "Blender Bases",
    "Coffee Maker Frames",
    "Kettle Bodies",
    "Toaster Frames",
    "Microwave Door Frames",
    "Refrigerator Door Handles",
    "Vacuum Cleaner Bodies",
    "Robotic Vacuum Chassis",
    "Iron Sole Plates",
    "Sewing Machine Frames",
    "Printer Enclosures",
    "Scanner Lids",
    "Projector Housings",
    "Camera Bodies",
    "Camera Lens Mounts",
    "Tripod Heads",
    "Tripod Legs",
    "Drone Controller Housings",
    "Bicycle Helmet Shells",
    "Skateboard Decks",
    "Roller Skate Frames",
    "Inline Skate Frames",

    # ── Medical & Healthcare ──────────────────────────────────────────────────
    "Orthopaedic Hip Implants",
    "Orthopaedic Knee Implants",
    "Spinal Fusion Cages",
    "Spinal Pedicle Screws",
    "Bone Plates",
    "Intramedullary Nails",
    "Bone Screws",
    "Dental Implants",
    "Dental Crowns",
    "Dental Bridges",
    "Dental Abutments",
    "Orthodontic Brackets",
    "Clear Aligner Trays",
    "Hearing Aid Shells",
    "Cochlear Implant Housings",
    "Prosthetic Limb Sockets",
    "Prosthetic Foot Structures",
    "Prosthetic Hand Mechanisms",
    "Exoskeleton Orthotics",
    "Surgical Instrument Handles",
    "Laparoscopic Tool Bodies",
    "Endoscope Shafts",
    "Biopsy Needle Guides",
    "Retractor Frames",
    "Clamp Jaws (Surgical)",
    "Forceps Bodies",
    "Scalpel Handles",
    "Needle Holders",
    "Surgical Stapler Frames",
    "Catheter Connectors",
    "Stent Geometries",
    "Heart Valve Frames",
    "Ventricular Assist Device Housings",
    "Pacemaker Enclosures",
    "Insulin Pump Housings",
    "Infusion Pump Bodies",
    "Syringe Bodies",
    "IV Pole Structures",
    "Hospital Bed Frames",
    "Wheelchair Frames",
    "Walking Frame Structures",
    "Crutch Handles",
    "Stretcher Frames",
    "Operating Table Structures",
    "CT Scanner Gantries",
    "MRI Bore Structures",
    "X-Ray Table Frames",
    "Radiation Shield Structures",
    "Microscope Stage Mechanisms",
    "Lab Centrifuge Rotors",
    "Pipette Tip Racks",
    "Microfluidic Chip Moulds",
    "Incubator Trays",
    "Autoclave Baskets",
    "Prosthetic Nose / Ear Shells",
    "Custom Orthotic Insoles",
    "Splints and Casts",
    "CPAP Mask Frames",
    "Nebuliser Housings",

    # ── Oil & Gas / Energy ────────────────────────────────────────────────────
    "Pipeline Flanges",
    "Subsea Pipeline Connectors",
    "Wellhead Equipment",
    "Christmas Tree Valves",
    "Blowout Preventer Frames",
    "Drill Bit Bodies",
    "Drill Collar Bodies",
    "Mud Motor Components",
    "Riser Joints",
    "Jumper Spools",
    "Pipeline Pigs",
    "Clamp Connectors",
    "Subsea Manifolds",
    "Topside Structures",
    "Flare Stack Supports",
    "Pressure Relief Valve Bodies",
    "Gas Separator Vessels",
    "Glycol Contactor Columns",
    "Compressor Skid Frames",
    "Pump Skid Frames",
    "LNG Storage Tank Shells",
    "Cryogenic Valve Bodies",
    "Heat Tracing Brackets",
    "Pig Launcher Barrels",
    "Geothermal Wellhead Components",
    "Nuclear Reactor Pressure Vessels",
    "Nuclear Fuel Rod Assemblies",
    "Nuclear Containment Structures",
    "Nuclear Waste Casks",

    # ── Mining & Heavy Equipment ──────────────────────────────────────────────
    "Excavator Buckets",
    "Excavator Arms",
    "Excavator Tracks",
    "Bulldozer Blades",
    "Dozer Undercarriages",
    "Wheel Loader Buckets",
    "Loader Arms",
    "Haul Truck Bodies",
    "Haul Truck Frames",
    "Drill Rig Masts",
    "Rock Drill Bodies",
    "Jaw Crusher Frames",
    "Cone Crusher Mantles",
    "Ball Mill Shells",
    "Rod Mill Shells",
    "SAG Mill Liners",
    "Thickener Tank Structures",
    "Flotation Cell Bodies",
    "Leach Tank Structures",
    "Longwall Shearer Bodies",
    "Continuous Miner Frames",
    "Roof Bolter Arms",
    "Mine Hoist Drums",
    "Winding Tower Frames",
    "Skip Buckets",
    "Man-riding Chair Structures",
    "Conveyor Gearbox Housings",

    # ── Agriculture & Farming ─────────────────────────────────────────────────
    "Tractor Chassis",
    "Tractor Cab Frames",
    "Plough Frames",
    "Disc Harrow Frames",
    "Seed Drill Frames",
    "Fertiliser Spreader Bodies",
    "Sprayer Boom Arms",
    "Combine Harvester Header Frames",
    "Combine Threshing Drums",
    "Baler Frames",
    "Round Baler Chambers",
    "Hay Raker Frames",
    "Silage Chopper Bodies",
    "Grain Auger Tubes",
    "Grain Cart Bodies",
    "Irrigation Pivot Structures",
    "Drip Tape Fittings",
    "Greenhouse Structures",
    "Livestock Feeder Troughs",
    "Livestock Gate Frames",
    "Milking Machine Components",
    "Egg Tray Structures",
    "Poultry Cage Frames",
    "Aquaculture Cage Structures",
    "Fish Feeder Mechanisms",
    "Soil Sampling Probes",
    "Agricultural Drone Frames",

    # ── Defence & Military ────────────────────────────────────────────────────
    "Rifle Receivers",
    "Handgun Frames",
    "Barrel Assemblies",
    "Suppressor Bodies",
    "Magazine Bodies",
    "Bipod Mounts",
    "Scope Mounts",
    "Tactical Rail Systems",
    "Grenade Launcher Frames",
    "Mortar Baseplates",
    "Artillery Barrel Mounts",
    "Tank Turret Structures",
    "Armoured Vehicle Door Frames",
    "Ballistic Shield Frames",
    "Body Armour Plate Carriers",
    "Helmet Shells",
    "Night Vision Mount Brackets",
    "Missile Airframes",
    "Missile Fin Assemblies",
    "Torpedo Body Structures",
    "Mine Casings",
    "Radar Antenna Structures",
    "Sonar Transducer Mounts",
    "Combat Vehicle Seats",
    "Parachute Harness Hardware",
    "Field Equipment Mounts",
    "Military Radio Enclosures",
    "EOD Tool Bodies",

    # ── Rail & Transportation ─────────────────────────────────────────────────
    "Railway Bogie Frames",
    "Wheelset Assemblies",
    "Coupler Bodies",
    "Buffer Housings",
    "Train Door Mechanisms",
    "Pantograph Structures",
    "Rail Fishplates",
    "Rail Clips",
    "Switch Blade Assemblies",
    "Crossing Frogs",
    "Train Seat Frames",
    "Overhead Line Equipment",
    "Locomotive Cab Structures",
    "Metro Car Shells",
    "Tram Bogie Frames",
    "Monorail Saddle Structures",
    "Maglev Guidance Rail",
    "Cable Car Grips",
    "Funicular Car Frames",
    "Roller Coaster Track Sections",
    "Roller Coaster Car Bodies",
    "Theme Park Ride Structures",
    "Airport Jetbridge Frames",
    "Luggage Carousel Frames",

    # ── Furniture & Interior Products ─────────────────────────────────────────
    "Chair Frames",
    "Table Legs",
    "Cabinet Carcasses",
    "Drawer Runners",
    "Hinge Mechanisms",
    "Door Knob Bodies",
    "Shelf Brackets",
    "Wardrobe Frames",
    "Bed Frames",
    "Sofa Frames",
    "Desk Frames",
    "Bookcase Structures",
    "Kitchen Cabinet Frames",
    "Kitchen Sink Mounts",
    "Bathroom Vanity Frames",
    "Mirror Frames",
    "Picture Frames",
    "Curtain Rail Systems",
    "Blind Mechanisms",
    "Office Chair Bases",
    "Office Chair Mechanisms",
    "Ergonomic Armrests",
    "Monitor Stand Frames",
    "Laptop Stand Structures",
    "Coat Rack Structures",
    "Wine Rack Frames",
    "Stair Tread Brackets",
    "Fireplace Surrounds",

    # ── Sports & Recreation ───────────────────────────────────────────────────
    "Golf Club Heads",
    "Golf Club Shafts",
    "Tennis Racket Frames",
    "Badminton Racket Frames",
    "Cricket Bat Mould",
    "Baseball Bat Geometry",
    "Ice Skate Blades",
    "Ski Boot Shells",
    "Ski Binding Plates",
    "Snowboard Core Geometry",
    "Surfboard Fin Systems",
    "Wakeboard Bindings",
    "Archery Bow Risers",
    "Compound Bow Cam Systems",
    "Crossbow Stocks",
    "Fishing Reel Frames",
    "Fishing Rod Guides",
    "Climbing Harness Hardware",
    "Carabiner Bodies",
    "Cam Device Lobes",
    "Ice Axe Heads",
    "Crampons Frames",
    "Bicycle Suspension Forks",
    "MTB Frame Geometry",
    "Road Bike Frame Structures",
    "Gym Equipment Frames",
    "Barbell Collar Bodies",
    "Weight Plate Geometry",
    "Dumbbell Handles",
    "Treadmill Frames",
    "Rowing Machine Structures",
    "Swimming Pool Lane Floats",
    "Diving Board Brackets",
    "Goal Post Structures",
    "Stadium Seat Frames",
    "Helmet Faceguards",
    "Shin Guard Shells",
    "Ice Hockey Stick Blades",
    "Lacrosse Stick Heads",

    # ── Jewellery & Watchmaking ───────────────────────────────────────────────
    "Ring Shanks",
    "Ring Settings",
    "Prong Settings",
    "Bezel Settings",
    "Pavé Settings",
    "Pendant Bodies",
    "Necklace Clasp Mechanisms",
    "Bracelet Links",
    "Earring Posts",
    "Brooch Frames",
    "Cufflink Bodies",
    "Tie Clip Structures",
    "Wristwatch Cases",
    "Wristwatch Dials",
    "Watch Crown Bodies",
    "Watch Bezel Rings",
    "Watch Strap Lugs",
    "Watch Movement Bridges",
    "Watch Mainspring Barrels",
    "Escapement Wheel Geometry",
    "Gear Train Wheels (Horology)",
    "Pocket Watch Cases",
    "Clock Movements",
    "Pendulum Bobs",
    "Clock Hands",
    "Trophy Bases",
    "Medal Bodies",
    "Challenge Coin Geometry",

    # ── Musical Instruments ───────────────────────────────────────────────────
    "Acoustic Guitar Bodies",
    "Electric Guitar Bodies",
    "Guitar Neck Profiles",
    "Guitar Bridge Geometry",
    "Violin Scroll Geometry",
    "Violin Bridge",
    "Cello Tailpiece",
    "Piano Action Mechanisms",
    "Piano Key Geometry",
    "Drum Shell Geometry",
    "Drum Hardware",
    "Cymbal Stand Bodies",
    "Trumpet Bell Shapes",
    "Saxophone Body Forms",
    "Clarinet Key Mechanisms",
    "Flute Headjoint Bodies",
    "Trombone Slide Assemblies",
    "Mouthpiece Geometry",
    "Microphone Capsule Housings",
    "Microphone Stand Structures",
    "Speaker Cabinet Structures",
    "Amplifier Chassis",
    "Effects Pedal Enclosures",
    "Guitar Strap Buttons",
    "Music Stand Structures",

    # ── Toys & Play ───────────────────────────────────────────────────────────
    "Action Figure Bodies",
    "Toy Car Bodies",
    "Toy Train Structures",
    "Building Block Connectors",
    "Puzzle Piece Geometry",
    "Board Game Pieces",
    "Dice Geometry",
    "Remote Control Car Chassis",
    "RC Boat Hulls",
    "Plastic Toy Moulds",
    "Doll House Structures",
    "Toy Robot Frames",
    "Spinning Top Geometry",
    "Yo-Yo Geometry",
    "Frisbee Geometry",
    "Kite Frame Structures",
    "Model Rocket Kits",
    "Fidget Spinner Bodies",
    "Cube Puzzle Mechanisms",
    "Marble Run Track Sections",

    # ── Fashion & Wearables ───────────────────────────────────────────────────
    "Shoe Sole Geometry",
    "Shoe Last Geometry",
    "Heel Structures",
    "Buckle Bodies",
    "Belt Keeper Loops",
    "Glasses Frames",
    "Sunglasses Temples",
    "Contact Lens Geometry",
    "Hat Brim Structures",
    "Zipper Pull Geometry",
    "Button Geometry",
    "Snap Fastener Bodies",
    "Sewing Machine Foot Attachments",
    "Shoulder Pad Inserts",
    "Corset Boning",
    "Handbag Frames",
    "Wallet Clasp Bodies",
    "Luggage Frame Structures",
    "Umbrella Frame Ribs",
    "Backpack Frame Stays",

    # ── Packaging & Containers ────────────────────────────────────────────────
    "Bottle Cap Geometry",
    "Bottle Neck Geometry",
    "Aerosol Can Bodies",
    "Spray Nozzle Geometry",
    "Blister Pack Moulds",
    "Clamshell Package Geometry",
    "Cosmetic Tube Geometry",
    "Lip Balm Stick Geometry",
    "Foundation Compact Shells",
    "Perfume Bottle Geometry",
    "Perfume Cap Design",
    "Jar Geometry",
    "Tin Can Geometry",
    "Folding Box Geometry",
    "Crate Structures",
    "Pallet Designs",
    "Drum Barrel Geometry",
    "IBC Tote Structures",
    "Ampoule Geometry",
    "Medical Blister Packs",
    "Childproof Cap Mechanisms",
    "Closure Liner Geometry",
    "Dispensing Pump Mechanisms",
    "Trigger Sprayer Bodies",

    # ── Food & Beverage Equipment ─────────────────────────────────────────────
    "Commercial Oven Structures",
    "Conveyor Oven Frames",
    "Mixing Bowl Geometry",
    "Dough Mixer Attachments",
    "Bread Mould Geometry",
    "Cookie Cutter Geometry",
    "Chocolate Mould Geometry",
    "Ice Cream Mould Geometry",
    "Pasta Die Geometry",
    "Meat Grinder Plates",
    "Slicing Machine Blades",
    "Filling Machine Nozzles",
    "Capping Machine Heads",
    "Labelling Machine Guides",
    "Bottling Line Conveyors",
    "Commercial Refrigeration Units",
    "Cold Room Panel Structures",
    "Industrial Dishwasher Frames",
    "Brewing Tank Structures",
    "Fermentation Vessel Geometry",
    "Distillation Column Structures",

    # ── Plumbing & HVAC ───────────────────────────────────────────────────────
    "Pipe Fittings",
    "Radiator Panels",
    "Fan Blade Geometry",
    "Fan Housing",
    "Air Handling Unit Structures",
    "Duct Work Sections",
    "Duct Flanges",
    "Duct Hangers",
    "Diffuser Grilles",
    "Louvre Panels",
    "Damper Blades",
    "VAV Box Structures",
    "Chiller Shells",
    "Cooling Tower Fill Media",
    "Expansion Vessel Geometry",
    "Tap Bodies",
    "Shower Head Geometry",
    "Toilet Cistern Internals",
    "Flush Valve Mechanisms",
    "Waste Trap Geometry",
    "Urinal Screens",
    "Manhole Ring Geometry",
    "Inspection Chamber Bodies",

    # ── Scientific & Laboratory ───────────────────────────────────────────────
    "Telescope Mirror Mounts",
    "Telescope Tube Assemblies",
    "Optical Bench Components",
    "Lens Mount Geometry",
    "Prism Holders",
    "Beam Splitter Mounts",
    "Spectrometer Bodies",
    "Cuvette Holders",
    "Microplate Frames",
    "Centrifuge Rotors",
    "Vacuum Chamber Structures",
    "Vacuum Flange Geometry",
    "Cryostat Structures",
    "Electromagnet Coil Formers",
    "Particle Accelerator Magnets",
    "Detector Housings",
    "Wind Tunnel Models",
    "Hydrodynamic Scale Models",
    "Seismometer Housings",
    "Gravimeter Cases",
    "Weather Station Enclosures",
    "Radiation Detector Probes",
    "Mass Spectrometer Inlet Probes",
    "NMR Tube Racks",

    # ── Textile & Apparel Machinery ───────────────────────────────────────────
    "Loom Frames",
    "Shuttle Bodies",
    "Heddle Frames",
    "Knitting Machine Needles",
    "Circular Knitting Cylinder",
    "Spinning Ring Geometry",
    "Bobbin Geometry",
    "Winding Machine Guides",
    "Embroidery Frame",
    "Overlock Machine Parts",
    "Cutting Machine Blades",
    "Plotter Cutter Heads",
    "Button Attaching Dies",

    # ── Printing & Publishing Machinery ──────────────────────────────────────
    "Printing Press Rollers",
    "Printing Press Frames",
    "Die Cutting Blades",
    "Embossing Dies",
    "Binding Machine Structures",
    "Laminator Rollers",
    "Inkjet Printhead Mounts",
    "Screen Printing Frames",
    "UV Curing Lamp Housings",
    "Paper Folding Machine Guides",

    # ── Construction Equipment ────────────────────────────────────────────────
    "Scaffolding Couplers",
    "Scaffolding Frames",
    "Scaffolding Boards",
    "Concrete Mixer Drums",
    "Concrete Pump Booms",
    "Tower Crane Masts",
    "Tower Crane Jibs",
    "Mobile Crane Booms",
    "Lifting Hook Bodies",
    "Shackle Bodies",
    "Spreader Beam Structures",
    "Formwork Prop Bodies",
    "Pile Driver Hammer Casings",
    "Trench Shoring Panels",
    "Road Roller Drums",
    "Paving Machine Screeds",
    "Asphalt Spreader Bodies",
    "Snow Plow Blades",
    "Grader Blade Frames",

    # ── Space & Emerging Tech ─────────────────────────────────────────────────
    "Lunar Lander Legs",
    "Mars Rover Chassis",
    "Asteroid Mining Tool Heads",
    "Space Habitat Structures",
    "Solar Sail Booms",
    "Ion Thruster Bodies",
    "Hall Effect Thruster Housings",
    "Tether Deployment Mechanisms",
    "Space Debris Capture Nets",
    "Hyperloop Capsule Shells",
    "Hyperloop Tube Sections",
    "Flying Car Frames",
    "eVTOL Rotor Arms",
    "eVTOL Fuselage",
    "Underwater Habitat Structures",
    "Deep Sea Mining Crawler Frames",
    "Bioreactor Vessel Geometry",
    "Organ-on-Chip Moulds",
    "Lab-Grown Tissue Scaffolds",
    "Microelectromechanical Systems (MEMS)",
    "Nano-scale Structural Components",
    "4D Printing Shape Memory Structures",
    "Topology Optimised Load Brackets",
    "Lattice Structure Components",
    "Metamaterial Cell Geometry",
]

# ── Stats ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"Total domains: {len(CAD_DOMAINS)}")
    for d in CAD_DOMAINS:
        print(f"  • {d}")
